services:
  - type: web
    name: dearest-llama
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NVIDIA_NIM_API_KEY
        sync: false
      - key: TOGETHER_AI_API_KEY # New environment variable for Together AI
        sync: false
      - key: BLUESKY_IDENTIFIER
        sync: false
      - key: BLUESKY_APP_PASSWORD
        sync: false
      - key: ADMIN_BLUESKY_HANDLE
        sync: false
      - key: TEXT_MODEL
        value: meta/llama-4-maverick-17b-128e-instruct
      - key: IMAGE_PROMPT_MODEL
        value: meta/llama-4-scout-17b-16e-instruct
      # IMAGE_GENERATION_MODEL is now hardcoded in index.js
      - key: TEXT_SYSTEM_PROMPT
        value: "You are part of a bot designed to respond to a conversation on Bluesky. You will write a reply, and another part of the bot will post it. Keep your responses under 300 characters."
      - key: IMAGE_PROMPT_SYSTEM_PROMPT
        value: "Create a prompt for an image model based on the following question and answer. If the prompt doesn't already have animals in it, add cats."
      - key: CHECK_INTERVAL
        value: "60000"
      - key: MAX_RETRIES
        value: "5"
      - key: BACKOFF_DELAY
        value: "60000"
      - key: MAX_REPLIED_POSTS
        value: "1000"
    healthCheckPath: /health
    scaling:
      minInstances: 1
      maxInstances: 1
